CREATE TABLE Players(
    player_id INT PRIMARY KEY,
    player_name TEXT,
    conc_player_name TEXT,
    team TEXT,
    position TEXT
);
CREATE TABLE PlayerStats(
    stat_id INT PRIMARY KEY,
    player_id INT,
    games_played INT,
    games_started INT,
    minutes_played INT,
    goals INT,
    accurate_pass_percentage REAL,
    assists INT,
    total_scoring_attempts INT,
    on_target_scoring_attempts INT,
    total_attacking_assists INT,
    tackles INT,
    fouls_committed INT,
    fouls_suffered INT,
    total_offside INT,
    yellow_cards INT,
    red_cards INT,
    accurate_passes INT,
    total_passes INT,
    crosses INT,
    assists_avg_over_90_mins REAL,
    long_balls INT,
    successful_short_passes INT,
    turnovers INT,
    goals_avg_over_90_mins REAL,
    penalty_kick_goals INT,
    penalty_kick_taken INT,
    penalty_kick_percentage REAL,
    accurate_shooting_percentage REAL,
    successful_dribble INT,
    dribble_percentage REAL,
    goals_and_assists INT,
    tackles_won INT,
    tackles_percentage REAL,
    interceptions INT,
    headed_duel INT,
    gk_saves INT,
    gk_long_ball_percentage REAL,
    gk_total_clearance INT,
    FOREIGN KEY (player_id) REFERENCES Players(player_id)
);